"use client";

import Link from "next/link";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CodeBlock } from "@/components/docs/code-block";

export default function RouterDocsPage() {
  return (
    <div className="mx-auto max-w-4xl px-6 py-12 md:px-8">
      <div className="mb-12 border-b pb-10">
        <h1 className="text-4xl font-bold text-foreground">
          Router Integration
        </h1>
        <p className="mt-4 text-lg text-muted-foreground">
          Advanced routing hooks for navigation, URL syncing, and state
          management, powered by{" "}
          <a
            href="https://tanstack.com/router/latest"
            target="_blank"
            rel="noopener noreferrer"
            className="font-medium underline underline-offset-4 hover:text-primary"
          >
            TanStack Router
          </a>
          .
        </p>
      </div>

      <div className="space-y-16 text-foreground">
        <section className="scroll-mt-20">
          <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
            Installation & Setup
          </h2>
          <div className="rounded-lg border border-amber-500/50 bg-amber-500/10 p-4 text-sm text-amber-500 mb-6 font-medium">
            Requirement: Your application must be wrapped in a TanStack{" "}
            <code>RouterProvider</code> for these hooks to function.
          </div>

          <div className="mt-2">
            <Tabs defaultValue="next">
              <TabsList>
                <TabsTrigger value="next">Next.js</TabsTrigger>
                <TabsTrigger value="vite">Vite / SPA</TabsTrigger>
              </TabsList>

              <TabsContent value="next" className="mt-4">
                <p className="text-sm text-muted-foreground mb-2">
                  <span className="font-semibold text-foreground">Step 1:</span>{" "}
                  Create <code>src/app/providers.tsx</code>
                </p>
                <div className="mb-6">
                  <CodeBlock
                    language="tsx"
                    code={`"use client";

import { RouterProvider, createRouter } from '@tanstack/react-router'
import { DataProviderProvider, defaultDataProvider } from "@/hooks";
import { routeTree } from '../routeTree.gen' // generated by "tsr watch"

const router = createRouter({ routeTree })

export function Providers({ children }) {
  return (
    <DataProviderProvider value={defaultDataProvider}>
      <RouterProvider router={router} />
      {children}
    </DataProviderProvider>
  )
}`}
                  />
                </div>

                <p className="text-sm text-muted-foreground mb-2">
                  <span className="font-semibold text-foreground">Step 2:</span>{" "}
                  Use in <code>src/app/layout.tsx</code> (App Router)
                </p>
                <CodeBlock
                  language="tsx"
                  code={`import { Providers } from "./providers";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}`}
                />
              </TabsContent>

              <TabsContent value="vite" className="mt-4">
                <p className="text-sm text-muted-foreground mb-2">
                  <code className="text-foreground font-semibold">
                    src/App.tsx
                  </code>{" "}
                  (or entry point)
                </p>
                <CodeBlock
                  language="tsx"
                  code={`// src/App.tsx
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { 
  DataProviderProvider, 
  createDataProvider,
  AuthProviderProvider,
  createAuthProvider
} from "@/hooks";

// Import your generated route tree
import { routeTree } from './routeTree.gen'

const router = createRouter({ routeTree })

// Configure providers with your URLs
const dataProvider = createDataProvider("https://api.example.com");
const authProvider = createAuthProvider("https://auth.example.com");

export default function App() {
  return (
    <AuthProviderProvider value={authProvider}>
      <DataProviderProvider value={dataProvider}>
        <RouterProvider router={router} />
      </DataProviderProvider>
    </AuthProviderProvider>
  )
}`}
                />
              </TabsContent>
            </Tabs>
          </div>
        </section>

        <hr className="border-border" />

        <section id="defining-routes" className="scroll-mt-20">
          <div className="mb-6">
            <h2 className="text-2xl font-bold mb-2">Defining Routes</h2>
            <div className="rounded-lg border border-amber-500/50 bg-amber-500/10 p-4 text-sm text-amber-500 mb-6 font-medium">
              <strong>Note:</strong> TanStack Router does not use JSX{" "}
              <code>&lt;Route&gt;</code> components like React Router. Instead,
              you build a <strong>Route Tree</strong> of objects.
            </div>
          </div>

          <div className="grid gap-6">
            <Tabs defaultValue="file">
              <TabsList>
                <TabsTrigger value="file">File-Based (Recommended)</TabsTrigger>
                <TabsTrigger value="code">Code-Based (Manual)</TabsTrigger>
              </TabsList>

              <TabsContent value="file" className="mt-4 space-y-4">
                <div className="rounded-lg border bg-card p-4">
                  <h3 className="font-semibold mb-2">1. Setup (One-time)</h3>
                  <p className="text-sm text-muted-foreground mb-3">
                    You need the TanStack Router CLI to generate the route tree.
                    By default, it looks for files in <code>src/routes</code>.
                  </p>
                  <div className="relative rounded-lg border bg-zinc-950 p-3 font-mono text-sm text-zinc-50 overflow-x-auto dark:bg-zinc-900 mb-4">
                    npm install -D @tanstack/router-cli
                  </div>

                  <h3 className="font-semibold mb-2">2. Running the CLI</h3>
                  <div className="text-sm text-foreground space-y-3">
                    <div>
                      <div className="font-medium text-green-400 mb-1">
                        Option A: Watch Mode (Recommended)
                      </div>
                      <p className="text-muted-foreground mb-2">
                        Run this in a <strong>separate terminal</strong> while
                        you work. It stays running and updates your routes{" "}
                        <em>instantly</em> whenever you add/change files.
                      </p>
                      <div className="relative rounded-lg border bg-zinc-950 p-2 font-mono text-sm text-zinc-50 dark:bg-zinc-900">
                        npx tsr watch
                      </div>
                    </div>

                    <div>
                      <div className="font-medium text-amber-400 mb-1">
                        Option B: One-time Generation
                      </div>
                      <p className="text-muted-foreground mb-2">
                        If you don't want a background process, run this{" "}
                        <em>manually</em> every time you add a file.
                      </p>
                      <div className="relative rounded-lg border bg-zinc-950 p-2 font-mono text-sm text-zinc-50 dark:bg-zinc-900">
                        npx tsr generate
                      </div>
                    </div>
                  </div>
                </div>

                <div className="border-t pt-4"></div>

                <p className="text-muted-foreground">
                  <strong>3. Creating Files</strong>
                  <br />
                  Once the watcher is running, creating a file automatically
                  creates a URL.
                </p>
                <div className="rounded-md bg-blue-500/10 p-4 border border-blue-500/20 text-sm text-blue-500 my-4">
                  <strong>Think of it like a file explorer:</strong> Just like
                  opening a folder on your computer changes your path (e.g.,{" "}
                  <code>Documents/Photos</code>), creating a folder in your code
                  changes the website URL (e.g., <code>/documents/photos</code>
                  ).
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="rounded-lg border bg-zinc-950 p-4 font-mono text-sm text-zinc-50 overflow-x-auto dark:bg-zinc-900">
                    <div className="text-xs text-muted-foreground mb-2 border-b border-zinc-800 pb-2">
                      Your Files (MUST be in <code>src/routes</code>)
                    </div>
                    <div className="grid grid-cols-[1fr_auto] gap-2 items-center">
                      <span className="text-amber-400">
                        src/routes/index.tsx
                      </span>{" "}
                      <span className="text-zinc-500">→</span>
                      <span className="text-amber-400">
                        src/routes/about.tsx
                      </span>{" "}
                      <span className="text-zinc-500">→</span>
                      <span className="text-amber-400">
                        src/routes/posts/index.tsx
                      </span>{" "}
                      <span className="text-zinc-500">→</span>
                      <span className="text-amber-400">
                        src/routes/posts/$id.tsx
                      </span>{" "}
                      <span className="text-zinc-500">→</span>
                    </div>
                  </div>
                  <div className="rounded-lg border bg-zinc-950 p-4 font-mono text-sm text-zinc-50 overflow-x-auto dark:bg-zinc-900">
                    <div className="text-xs text-muted-foreground mb-2 border-b border-zinc-800 pb-2">
                      Resulting URLs
                    </div>
                    <div className="grid grid-cols-1 gap-2">
                      <span className="text-green-400">/</span>
                      <span className="text-green-400">/about</span>
                      <span className="text-green-400">/posts</span>
                      <span className="text-green-400">/posts/123</span>
                    </div>
                  </div>
                </div>
                <p className="text-sm text-muted-foreground">
                  The CLI tool watches your folder and generates the{" "}
                  <code>routeTree</code> for you. You just need to create the
                  files!
                </p>

                <div className="mt-6 rounded-lg border border-zinc-200 bg-zinc-50 p-4 dark:border-zinc-800 dark:bg-zinc-900/50">
                  <h4 className="font-semibold text-sm mb-2">
                    Common Questions
                  </h4>
                  <ul className="text-sm text-muted-foreground list-disc pl-4 space-y-1">
                    <li>
                      <strong>Renaming Files:</strong> If you rename{" "}
                      <code>index.tsx</code> to <code>home.tsx</code>, the CLI{" "}
                      <em>instantly</em> updates the route from <code>/</code>{" "}
                      to <code>/home</code>.
                    </li>
                    <li>
                      <strong>Moving Files:</strong> Dragging a file into a
                      folder (e.g., <code>about.tsx</code> →{" "}
                      <code>company/about.tsx</code>) automatically changes the
                      URL to <code>/company/about</code>.
                    </li>
                  </ul>
                </div>
              </TabsContent>

              <TabsContent value="code" className="mt-4 space-y-4">
                <p className="text-muted-foreground">
                  If you prefer to define routes manually in code:
                </p>
                <CodeBlock
                  language="tsx"
                  code={`import { createRootRoute, createRoute, createRouter } from '@tanstack/react-router'

// 1. Create Root
const rootRoute = createRootRoute({ component: Layout })

// 2. Create Children
const postsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/posts',
  component: PostList,
})

const postShowRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/posts/$id', // Use $ for params, not :id
  component: PostShow,
})

// 3. Build Tree
const routeTree = rootRoute.addChildren([postsRoute, postShowRoute])

// 4. Create Router
const router = createRouter({ routeTree })`}
                />
              </TabsContent>
            </Tabs>
          </div>
        </section>

        <hr className="border-border" />

        <section id="use-go" className="scroll-mt-20">
          <div className="mb-6">
            <h2 className="text-2xl font-bold mb-2">useGo</h2>
            <p className="text-muted-foreground">
              A detailed navigation hook that simplifies moving between pages
              and updating query parameters (like filters or sorting) without
              wiping existing state.
            </p>
          </div>

          <div className="grid gap-6 lg:grid-cols-2">
            <div className="space-y-4">
              <h3 className="font-semibold text-foreground">Usage</h3>
              <CodeBlock
                language="tsx"
                code={`const go = useGo();

// 1. Navigate to a path
go({ to: "/posts" });

// 2. Update query params (e.g. filters)
go({ 
  query: { 
    status: "published", 
    sort: "createdAt" 
  },
  type: "replace" // Don't add to history
});

// 3. Navigate with params
go({ 
  to: "/posts/edit/1", 
  query: { tab: "details" } 
});`}
              />
            </div>

            <div className="space-y-4">
              <h3 className="font-semibold text-foreground">API Reference</h3>
              <div className="rounded-lg border bg-card text-sm">
                <table className="w-full text-left">
                  <thead className="border-b bg-muted/50">
                    <tr>
                      <th className="p-3 font-medium">Prop</th>
                      <th className="p-3 font-medium">Type</th>
                      <th className="p-3 font-medium">Description</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y">
                    <tr>
                      <td className="p-3 font-mono text-xs">to</td>
                      <td className="p-3 text-xs text-muted-foreground">
                        string
                      </td>
                      <td className="p-3">
                        Target path (e.g. <code>/users</code>).
                      </td>
                    </tr>
                    <tr>
                      <td className="p-3 font-mono text-xs">query</td>
                      <td className="p-3 text-xs text-muted-foreground">
                        object
                      </td>
                      <td className="p-3">
                        Object of query parameters to merge.
                      </td>
                    </tr>
                    <tr>
                      <td className="p-3 font-mono text-xs">type</td>
                      <td className="p-3 text-xs text-muted-foreground">
                        enum
                      </td>
                      <td className="p-3">
                        <code>"push"</code> (default) or <code>"replace"</code>.
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </section>

        <hr className="border-border" />

        <section id="use-parsed" className="scroll-mt-20">
          <div className="mb-6">
            <h2 className="text-2xl font-bold mb-2">useParsed</h2>
            <p className="text-muted-foreground">
              Parses the current URL to infer the <code>resource</code>,{" "}
              <code>action</code>, <code>id</code>, and raw <code>params</code>.
              Useful for building generic layouts or breadcrumbs.
            </p>
          </div>

          <div className="grid gap-6 lg:grid-cols-2">
            <div className="space-y-4">
              <h3 className="font-semibold text-foreground">Example Output</h3>
              <CodeBlock
                language="json"
                code={`// URL: /products/edit/123?tab=price

{
  "resource": "products",
  "action": "edit",
  "id": "123",
  "pathname": "/products/edit/123",
  "params": {
    "tab": "price"
  }
}`}
              />
            </div>
            <div className="space-y-4">
              <h3 className="font-semibold text-foreground">Usage</h3>
              <CodeBlock
                language="tsx"
                code={`const { 
  id, 
  resource, 
  params 
} = useParsed();

if (resource === "products") {
   // ...
}`}
              />
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
